services:
  user-gateway:
    image: "hzl277341642/user-gateway:latest"
    build: ./packages/apps/ics-server-api-gateway/user-gateway
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  admin-gateway:
    image: "hzl277341642/admin-gateway:latest"
    build: ./packages/apps/ics-server-api-gateway/admin-gateway
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production