name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker to run Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images using Docker Compose
        run: docker-compose build

      - name: Tag user-gateway image
        run: docker tag microarchtemplate-user-gateway:latest ${{ secrets.DOCKER_USERNAME }}/user-gateway:latest

      - name: Tag admin-gateway image
        run: docker tag microarchtemplate-admin-gateway:latest ${{ secrets.DOCKER_USERNAME }}/admin-gateway:latest

      - name: Push user-gateway image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-gateway:latest

      - name: Push admin-gateway image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/admin-gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          ssh -o StrictHostKeyChecking=no root@155.94.204.39 "docker pull ${{ secrets.DOCKER_USERNAME }}/user-gateway:latest && docker stop ics-server-user-gateway && docker rm ics-server-user-gateway && docker run -d --name ics-server-user-gateway -p 3001:3000 ${{ secrets.DOCKER_USERNAME }}/user-gateway:latest"
          ssh -o StrictHostKeyChecking=no root@155.94.​⬤