name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker to run Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and start services using Docker Compose
        run: docker-compose up --build -d

      - name: Push Docker image to Docker Hub
        run: docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          ssh root@155.94.204.39 "docker pull hzl277341642/ics-server-user-gateway:latest && docker stop ics-server-user-gateway && docker rm ics-server-user-gateway && docker run -d --name ics-server-user-gateway -p 3001:3000 hzl277341642/ics-server-user-gateway:latest"